### ISSUE TITLE
GetCapabilities should exclude missing texts and texts without citations

### ISSUE THREAD

**Issue by balmas** [Capitains/Nautilus#21]
I don't think there is any value in having GetCapabilities include a text in the inventory if it can't actually be served.

**Comment by PonteIneptique** [comment]
I am not totally ok with this one and I'll tell you why. Currently, Perseids use texts which have no citation because they want to allow creation of a text. I am fine if you say that something CTS should not do (and DTS), but I want to be sure this is not for "bad" reason that we implement that.

For example, if this is an issue with showing it on Nemo, I'd find it actually way better to fix this by not displaying them on Nemo.

**Comment by balmas** [comment]
I thought about that and originally went the way of implementing it as an argument to parse but thats actually a different case. In the Perseids case we want to be able to have a work without any edition but what I fixed in Nautilus was the situation where the edition or translation is present in the inventory without an online element.

**Comment by balmas** [comment]
Or, to be more precise, with an *empty* online element

**Comment by PonteIneptique** [comment]
Then I am fine :)
Could you bump Nautilus version then ? I'll merge when you bump :)

(And that makes me think : we actually also need this thing for Nemo)

**Comment by balmas** [comment]
version bumped. I think.
