### ISSUE TITLE
clarify CTS version (and missing/additional attributes)

### ISSUE THREAD

**Issue by jtauber** [Capitains/Nautilus#50]
What version of the CTS protocol spec is implemented?

I noticed that elements that I would have expected to see a `tiversion` on, do not have them and I also noticed that there are attributes like `groupUrn` and `workUrn` in the response to a `GetCapabilities` which aren't defined in the 5.0.rc.1 schema (which seems to be what https://github.com/cite-architecture/cts_spec/tree/master/reply_schemas is for, even though the written spec is labeled 5.0.rc.2 and 5.0.rc.3 is mentioned).

If the issue is with the `cts_spec` repo, I can take it up there but wanted to get the answer in the context of Nautilus first.

**Comment by PonteIneptique** [comment]
We are up with 5.0.rc.2 or 3 normally.

Note that there is differences, mostly because the original system has some important but not clear area that fails to match their own description. If you check https://github.com/cite-architecture/cts_spec/issues/15, you'll see for example (that I never had an answer to this question but also) that xml:lang should be supported but is not. It is extremely important to understand the lack of communication with the original standard creator.

Now that it is noted, you are indeed right that I should add tiversion :)

**Comment by PonteIneptique** [comment]
Actually, looking at the repo from cite-architecture, only TextInventory should have it, which is super weird, given that it the API version and not the text inventory version (I think ?)

**Comment by jtauber** [comment]
So it would be correct to say, though, that the spec and the schema are out of sync? I noticed some other issues with the schema (such as defining `metadata` in `TextInventory.rng` but not using it). I can take those issues up in the `cts_spec` repo issues.

**Comment by PonteIneptique** [comment]
The spec and the schema have always been more or less out of sync unfortunately.

Good luck having an answer ! :) 

I appreciate though you opening an issue here, feel free to come back :)

**Comment by PonteIneptique** [comment]
That was at least the experience of my former dev manager and myself. Hope it is not the same for you :)
